### ISSUE TITLE
Issues with multi-GPU trainings on runpod kohya template

### ISSUE THREAD

**Issue by rafstahelin** [ashleykleynhans/kohya-docker#12]
On runpod when renting multiple gpu’s to run trainings, for instance 4x gpu’s, does one need a minimum cpu/ram setup? Is there also with accelerate the need to use a specific setting to cover this demanding performance? I am getting glitchy Denoise in the samples.

It used to work for me using CUDA=n command.

**Comment by ashleykleynhans** [comment]
Maybe due to CUDA version, the base image has changed from CUDA 11.8 to CUDA 12.1,  because that is the only thing that has changed.

However, according to [sd-scripts repo](https://github.com/kohya-ss/sd-scripts), you should be able to use CUDA 12:
<img width="831" alt="Screenshot 2024-05-31 at 21 30 19" src="https://github.com/ashleykleynhans/kohya-docker/assets/886709/7ca711aa-c90b-446b-981a-78a5ded16e56">

So I suggest logging a GitHub issue there to ask about this, because I have not used multiple GPU trainings.

**Comment by ashleykleynhans** [comment]
Maybe its because I installed Torch 2.3.0 instead of 2.1.2, I'll do a new build if you don't mind testing it.

**Comment by rafstahelin** [comment]
Yea I'll test thanks lmk 

And I'll post on sd

**Comment by ashleykleynhans** [comment]
@rafstahelin I have released template version 6.0.4 which reverts the torch and xformers version, Would you mind trying again please?

**Comment by ashleykleynhans** [comment]
Oh sorry, I was confused, the Kohya template is still the same, nothing has changed. I was confused and thought you were using the Ultimate template, which has now had torch and xformers reverted but it doesn't apply to this template.  I suggest logging an issue in the sd-scripts repo if you have not already done so.

**Comment by rafstahelin** [comment]
Yes I noticed on kohya it didn't change 
Must be something else the problem 
Thanks tho
