### ISSUE TITLE
Runpod Kohya Finetune process gets killed on launch

### ISSUE THREAD

**Issue by rafstahelin** [ashleykleynhans/kohya-docker#7]
Runpod Kohya Finetune process gets killed on launch

This might be related to the recent update to 23.1 as it wasnt happening before. Could it be related to the Torch 2.1.2 change?

![image](https://github.com/ashleykleynhans/kohya-docker/assets/64715158/9ff3382c-58e9-4fbd-870a-0a96407e43dd)

![image](https://github.com/ashleykleynhans/kohya-docker/assets/64715158/5e45ee75-2733-4a8c-b613-b6238b3cb157)

I do not see any other messages other than "Killed"

**Comment by ashleykleynhans** [comment]
How much system/CPU memory/RAM does your pod have?  This happens when the Linux kernel kills off your pod due to running out of memory (not VRAM).  If your pod has sufficient memory, log an issue in the the [Kohya sd-scripts repo](https://github.com/kohya-ss/sd-scripts) because Bernard only provides a GUI for the scripts and I only provide a Docker image for the GUI.

**Comment by rafstahelin** [comment]
> How much system/CPU memory/RAM does your pod have? This happens when the Linux kernel kills off your pod due to running out of memory (not VRAM). If your pod has sufficient memory, log an issue in the the [Kohya sd-scripts repo](https://github.com/kohya-ss/sd-scripts) because Bernard only provides a GUI for the scripts and I only provide a Docker image for the GUI.

Oh I see, I am running an A100 80GB VRAM. But you know what, its possibly an AdamW8bit issue
Seems to no longer be supported for FUll Fine Tuning. Going to close this as that seems to be the issue

**Comment by rafstahelin** [comment]
thanks!

**Comment by ashleykleynhans** [comment]
Its been determined that the optimizer is the issue.
